//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhasmophobiaChallenge.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Discord : global::System.Configuration.ApplicationSettingsBase {
        
        private static Discord defaultInstance = ((Discord)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Discord())));
        
        public static Discord Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ODA2MTMwMzg4NjIyNzcwMTk4.YBk9bQ.s40R8XFFwxI0TLRTavx7fYEeUVA")]
        public string Token {
            get {
                return ((string)(this["Token"]));
            }
            set {
                this["Token"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("803015136075186188")]
        public ulong ServerID {
            get {
                return ((ulong)(this["ServerID"]));
            }
            set {
                this["ServerID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("803018830485389403")]
        public ulong ChallengeChannelID {
            get {
                return ((ulong)(this["ChallengeChannelID"]));
            }
            set {
                this["ChallengeChannelID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("178060019206586369")]
        public ulong CurrentMemberID {
            get {
                return ((ulong)(this["CurrentMemberID"]));
            }
            set {
                this["CurrentMemberID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("803015204610900018")]
        public ulong WelcomeChannelID {
            get {
                return ((ulong)(this["WelcomeChannelID"]));
            }
            set {
                this["WelcomeChannelID"] = value;
            }
        }
    }
}
